# @package _global_

# specify here default training configuration
defaults:
  - trainer: default.yaml
  - model: default.yaml
  - datamodule: default.yaml
  - callbacks: default.yaml # set this to null if you don't want to use callbacks
  - logger: wandb.yaml # set logger here or use command line (e.g. `python run.py logger=wandb`)
  - hydra: default.yaml

# Before training, the samples are run through PVNet. The samples are saved under this directory
sample_save_dir: /home/jamesfulton/repos/PVNet_summation/presaved_saved_samples

work_dir: ${hydra:runtime.cwd}

model_name: "default"

seed: 2727831
