# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  project: "PLACEHOLDER"
  name: "${model_name}"
  save_dir: "PLACEHOLDER"
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  # entity: ""  # set to name of your wandb team or just remove it
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
